stages:
  - build
  - lint

cache:
  paths:
    - .tmp/
    - vendor/
    - app/

composer:
  stage: build
  image: composer:2.4
  # Some helpful debugging
  before_script:
    - php -v
    - composer --version
  script:
    - composer install --ignore-platform-reqs

phpstan:
  stage: lint
  image:
    name: ghcr.io/phpstan/phpstan
    entrypoint: ['']
  needs:
    - composer
  interruptible: true
  script: |
    set +euo pipefail  # don't abort if any following command fails
    vendor/bin/phpstan analyse --memory-limit=4G --error-format=gitlab > logs/phpstan.json
    vendor/bin/phpstan analyse --memory-limit=4G --error-format=junit > logs/phpstan-junit.xml
  artifacts:
    when: always
    paths:
      - logs/phpstan-junit.xml
      - logs/phpstan.json
    reports:
      junit: logs/phpstan-junit.xml
      codequality: logs/phpstan.json
