stages:
  - build
  - lint

cache:
  paths:
    - .tmp/
    - vendor/
    - app/

composer:
  stage: build
  image: composer:2.4
  # Some helpful debugging
  before_script:
    - php -v
    - composer --version
  script:
    - composer install --ignore-platform-reqs

phpstan:
  stage: lint
  image:
    name: ghcr.io/phpstan/phpstan
    entrypoint: ['']
  script: |
    vendor/bin/phpstan analyse --configuration=phpstan.dist.neon --memory-limit=4G
