name: linting

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {
  contents: read
}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  phpstan:
    name: "🧹 PHPSTAN"
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: "🧹 Run PHPStan Static Analysis"
        uses: docker://oskarstark/phpstan-ga:latest
        env:
          REQUIRE_DEV: true
